Changed ./submodules to ./bits

diff --git a/chownif b/chownif
--- a/chownif
+++ b/chownif
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 
 CHOWN_OUTPUT=/tmp/chown.log
 OWNER=${OWNER-$USER}
@@ -8,7 +8,7 @@ DIR_OR_FILE=$1
 
 if [[ "$USER" != "$OWNER" ]] || [[ "$FORCE" == "true" ]]; then
   SCRIPT_OUTPUT=$(chown -R $OWNER $DIR_OR_FILE > $CHOWN_OUTPUT 2>&1)
-  ERROR="Unable to chown to $OWNER $DIR_OR_FILE due to ..." ./submodules/bootstrap/failonerrors $? $CHOWN_OUTPUT
+  ERROR="Unable to chown to $OWNER $DIR_OR_FILE due to ..." ./bits/bootstrap/failonerrors $? $CHOWN_OUTPUT
   [ $? -ne 0 ] && exit 1
   debug "  -- Set ownership (was forced? $FORCE) to $OWNER ($DIR_OR_FILE)"
 else
diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 
 #-----------
 # Configurations
@@ -16,9 +16,9 @@ notify "Install bootstrap..."
 
 BOOTSTRAP_OUTPUT=/tmp/bootstrap.log
 
-OWNER=$OWNER ./submodules/bootstrap/mkdir BIN_DIR
+OWNER=$OWNER ./bits/bootstrap/mkdir BIN_DIR
 
-./submodules/bootstrap/cp ./submodules/bootstrap/files/helloworld $BIN_DIR/helloworld
+./bits/bootstrap/cp ./bits/bootstrap/files/helloworld $BIN_DIR/helloworld
 debug "  -- Adding $BIN_DIR/helloworld"
 chmod 755 $BIN_DIR/helloworld
 debug "  -- Adding $BIN_DIR/helloworld"
@@ -31,13 +31,13 @@ else
 fi
 
 debug "  -- Making logger available on node"
-./submodules/bootstrap/cp ./submodules/bootstrap/logging $BIN_DIR/logging
+./bits/bootstrap/cp ./bits/bootstrap/logging $BIN_DIR/logging
 
 debug "  -- Making capbashenv available on node"
-./submodules/bootstrap/cp ./submodules/bootstrap/env $BIN_DIR/capbashenv
+./bits/bootstrap/cp ./bits/bootstrap/env $BIN_DIR/capbashenv
 
 debug "  -- Making resolvevars available on node"
-./submodules/bootstrap/cp ./submodules/bootstrap/resolvevars $BIN_DIR/resolvevars
+./bits/bootstrap/cp ./bits/bootstrap/resolvevars $BIN_DIR/resolvevars
 
 if [[ "`which wget 2> /dev/null`" == "" ]]; then
   if [[ "$OS" == "ubuntu" ]]; then
@@ -53,7 +53,7 @@ if [[ "`which wget 2> /dev/null`" == "" ]]; then
     else
       notify "  -- Installing wget via brew"
       SCRIPT_OUTPUT=$(brew install -y wget > $BOOTSTRAP_OUTPUT 2>&1)
-      ERROR="Unable to install wget via brew due to ..." ./submodules/bootstrap/failonerrors $? $BOOTSTRAP_OUTPUT
+      ERROR="Unable to install wget via brew due to ..." ./bits/bootstrap/failonerrors $? $BOOTSTRAP_OUTPUT
       [ $? -ne 0 ] && exit 1
       debug $SCRIPT_OUTPUT
     fi
diff --git a/mkdir b/mkdir
--- a/mkdir
+++ b/mkdir
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 set -euo pipefail ; IFS=$'\n\t'
 
 MKDIR_OUTPUT=/tmp/mkdir.log
@@ -21,11 +21,11 @@ do
 
   if [ ! -e $DIR ] ; then
     SCRIPT_OUTPUT=$(mkdir -p ${DIR} > $MKDIR_OUTPUT 2>&1)
-    ERROR="Unable to mkdir -p ${DIR} due to ..." ./submodules/bootstrap/failonerrors $? $MKDIR_OUTPUT
+    ERROR="Unable to mkdir -p ${DIR} due to ..." ./bits/bootstrap/failonerrors $? $MKDIR_OUTPUT
     [ $? -ne 0 ] && exit 1
     debug "  -- Created $VARIABLE ($DIR)"
 
-    OWNER=$OWNER ./submodules/bootstrap/chownif $DIR
+    OWNER=$OWNER ./bits/bootstrap/chownif $DIR
     [ $? -ne 0 ] && exit 1
   else
     debug "  -- Re-using $VARIABLE ($DIR)"
diff --git a/touch b/touch
--- a/touch
+++ b/touch
@@ -1,5 +1,5 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 set -euo pipefail ; IFS=$'\n\t'
 
 TOUCH_OUTPUT=/tmp/touch.log
@@ -7,11 +7,11 @@ OWNER=${OWNER-$USER}
 FILE=$1
 
 SCRIPT_OUTPUT=$(touch ${FILE} > $TOUCH_OUTPUT 2>&1)
-ERROR="Unable to touch ${FILE} due to ..." ./submodules/bootstrap/failonerrors $? $TOUCH_OUTPUT
+ERROR="Unable to touch ${FILE} due to ..." ./bits/bootstrap/failonerrors $? $TOUCH_OUTPUT
 [ $? -ne 0 ] && exit 1
 debug "  -- Touched ${FILE}"
 if [[ "$OWNER" != "$USER" ]]; then
   SCRIPT_OUTPUT=$(chown $OWNER $FILE > $TOUCH_OUTPUT 2>&1)
-  ERROR="Unable to chown to $OWNER ${FILE} due to ..." ./submodules/bootstrap/failonerrors $? $TOUCH_OUTPUT
+  ERROR="Unable to chown to $OWNER ${FILE} due to ..." ./bits/bootstrap/failonerrors $? $TOUCH_OUTPUT
   [ $? -ne 0 ] && exit 1
 fi
