[CD-15800] added an uploademl to push EML to huginn (which pushing to apollo

diff --git a/failonerrors b/failonerrors
--- a/failonerrors
+++ b/failonerrors
@@ -8,6 +8,10 @@ if [ $1 -ne 0 ] ; then
     error_all $2
   fi
   exit 1
+elif [ ! -z $2 ] && [[ `cat $2 | grep "HTTP/1.1 500 Internal Server Error"` != "" ]] ; then
+  error "$ERROR"
+  error_all $2
+  exit 1
 else
   debug_all $2
 fi
